name: pgats-simple

releases:
- name: postgres
  version: YOUR_RELEASE_VERSION
- name: os-conf
  version: latest

stemcells:
- alias: linux
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: postgres
  instances: 1
  azs: [YOUR_AZ_LIST]
  networks:
  - name: YOUR_NETWORK
  jobs:
  - name: user_add
    release: os-conf
    properties:
      users:
      - name: ((testuser_name))
        public_key: ((sshkey.public_key))
  - name: postgres
    release: postgres
    provides:
      postgres: {as: postgres-database}
    properties:
      databases:
        port: 5524
        tls: "((postgres_cert))"
        databases:
        - citext: false
          name: sandbox
        - citext: false
          name: sandbox2
        max_connections: 111
        additional_config:
          shared_buffers: 32768
        roles:
        - name: aaa
          common_name: aaa_2
        - name: ((defuser_name))
          password: ((defuser_password))
        - name: ((certs_matching_name))
        - name: ((certs_mapped_name))
          common_name: ((certs_mapped_cn))
        - name: ((superuser_name))
          password: ((superuser_password))
          permissions:
          - "SUPERUSER"
          - "CONNECTION LIMIT 33"
          - "VALID UNTIL 'May 5 12:00:00 2025 +1'"
        trust_local_connections: false
  persistent_disk_type: YOUR_DISK_TYPE
  vm_type: YOUR_VM_TYPE
  stemcell: linux
  env:
    bosh:
      keep_root_password: true

update:
  canaries: 1
  canary_watch_time: 30000-600000
  max_in_flight: 1
  serial: true
  update_watch_time: 5000-600000

variables:
- name: sshkey
  type: ssh
- name: postgres_ca
  type: certificate
  options:
    is_ca: true
    common_name: postgres_ca
- name: postgres_cert
  type: certificate
  options:
    ca: postgres_ca
    common_name: ((postgres_host))
    alternative_names: [((postgres_host))]
    extended_key_usage:
    - server_auth
- name: ((certs_matching_certs))
  type: certificate
  options:
    ca: postgres_ca
    common_name: ((certs_matching_name))
    alternative_names: []
    extended_key_usage:
    - server_auth
    - client_auth
- name: ((certs_mapped_certs))
  type: certificate
  options:
    ca: postgres_ca
    common_name: ((certs_mapped_cn))
    alternative_names: []
    extended_key_usage:
    - server_auth
    - client_auth
- name: ((certs_wrong_certs))
  type: certificate
  options:
    ca: postgres_ca
    common_name: ((certs_wrong_cn))
    alternative_names: []
    extended_key_usage:
    - server_auth
    - client_auth
- name: ((certs_bad_ca))
  type: certificate
  options:
    is_ca: true
    common_name: bad_ca
